spring:
  datasource:
    #?serverTimezone=UTC???????
    url: jdbc:mysql://localhost:3306/mysql_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1123581321
mybatis:
  mapper-locations: classpath:mapper/*